server:
  port: 8080

spring:
  application:
    name: order-api

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%-3level] %msg %n%wEx"
  level:
    root: INFO
    org.springframework: WARN
    software.amazon.awssdk: WARN
